import React from "react";
import AgentRecentChatsPopover from "../../agent/AgentRecentChatsPopover";
import AgentHistorySearchDialog from "../agent/AgentHistorySearchDialog";
import ProfilePage from "../../pages/ProfilePage";
import OptimizePage from "../../pages/OptimizePage";
import LiteraturePage from "../../pages/LiteraturePage";
import TrainingPage from "../../pages/TrainingPage";

type RagAppOverlaysProps = Record<string, any>;

export default function RagAppOverlays(props: RagAppOverlaysProps) {
  const {
    isAgentMode,
    agentSidebarCollapsed,
    agentRecentChatsOpen,
    recentAgentConversations,
    agentSessionId,
    setAgentRecentChatsOpen,
    selectAgentConversation,
    agentHistorySearchOpen,
    agentHistorySearch,
    filteredAgentConversations,
    setAgentHistorySearch,
    setAgentHistorySearchOpen,
    startNewAgentConversation,
    showProfileCenter,
    setShowProfileCenter,
    profileInitial,
    profileUsername,
    profileTab,
    setProfileTab,
    profileError,
    setProfileError,
    llmDraftDirty,
    llmProvider,
    setLlmProvider,
    llmApiKey,
    setLlmApiKey,
    llmDisplayName,
    setLlmDisplayName,
    customProviderNames,
    llmBaseUrl,
    setLlmBaseUrl,
    llmModelName,
    setLlmModelName,
    llmModelsLoading,
    profileLlmModels,
    llmModelsNote,
    setLlmModels,
    loadLlmConfig,
    loadLlmModels,
    profileInfo,
    saveProfileLlmConfig,
    profileSaving,
    labCardTone,
    labRetrievalAvailable,
    labOptimizationAvailable,
    labServiceStatus,
    handleLabServiceAction,
    labServiceLoading,
    isDslAdmin,
    saveAuthSecurityConfig,
    securitySaving,
    authSecurityConfig,
    setAuthSecurityConfig,
    knowledgeBaseSecurityConfig,
    setKnowledgeBaseSecurityConfig,
    saveKnowledgeBaseSecurityConfig,
    mineruProcessingConfig,
    mineruUsage,
    setMineruProcessingConfig,
    mineruApiKey,
    setMineruApiKey,
    saveMineruProcessingConfig,
    retrievalModelsConfig,
    setRetrievalModelsConfig,
    retrievalApiKey,
    setRetrievalApiKey,
    saveRetrievalModelsConfig,
    turnstileEnabled,
    setTurnstileEnabled,
    turnstileSiteKey,
    setTurnstileSiteKey,
    turnstileSecretKey,
    setTurnstileSecretKey,
    turnstileConfig,
    saveTurnstileAdminConfig,
    turnstileSaving,
    captchaConfig,
    captchaProvider,
    setCaptchaProvider,
    geetestCaptchaId,
    setGeetestCaptchaId,
    geetestPrivateKey,
    setGeetestPrivateKey,
    saveCaptchaAdminConfig,
    showOptimizer,
    setTrainingEntrySource,
    setShowOptimizer,
    setShowTraining,
    hasOptimizerData,
    optimizing,
    optimizeResults,
    optimizeResult,
    optimizerRestoring,
    handleToggleAllStandards,
    selectedStandardIdx,
    activeOptimizerStandardRecords,
    activeOptimizerStandardColumns,
    handleSelectStandard,
    targetYield,
    setTargetYield,
    targetTensile,
    setTargetTensile,
    targetElong,
    setTargetElong,
    optimizeAlgorithm,
    setOptimizeAlgorithm,
    optimizeMaxiter,
    setOptimizeMaxiter,
    optimizePopsize,
    setOptimizePopsize,
    handleOptimize,
    optimizeProgress,
    requestOptimizeCancel,
    optimizeStopping,
    optimizeError,
    currentOptimizingIdx,
    setActiveResultTab,
    activeResultTab,
    optimizeLogs,
    perRecordLogs,
    tabTransition,
    tabViewMode,
    setTabViewMode,
    paretoIdx,
    setParetoIdx,
    exportingScheme,
    setExportingScheme,
    showLiterature,
    knowledgeViewMode,
    openKnowledgeCreate,
    openKnowledgeAppend,
    openKnowledgeDetail,
    knowledgeStep,
    setKnowledgeStep,
    knowledgeName,
    setKnowledgeName,
    knowledgeFolder,
    setKnowledgeFolder,
    knowledgeUploadedFiles,
    knowledgeUploadBusy,
    litFolders,
    litFoldersLoading,
    litFoldersLoaded,
    fetchLitFolders,
    literatureFiles,
    literatureFilesLoading,
    selectedLiteratureFile,
    setSelectedLiteratureFile,
    literatureFilePreview,
    literaturePreviewLoading,
    litJobs,
    canContinueKnowledgeUpload,
    litLoading,
    expandedJobId,
    expandedJobLogs,
    knowledgeParseMode,
    setKnowledgeParseMode,
    knowledgeExtractImages,
    setKnowledgeExtractImages,
    knowledgeExtractOcr,
    setKnowledgeExtractOcr,
    knowledgeExtractTables,
    setKnowledgeExtractTables,
    knowledgeEnableFormula,
    setKnowledgeEnableFormula,
    knowledgePageRanges,
    setKnowledgePageRanges,
    knowledgeFilterText,
    setKnowledgeFilterText,
    knowledgeSegmentMode,
    setKnowledgeSegmentMode,
    knowledgeMaxChunkSize,
    setKnowledgeMaxChunkSize,
    knowledgeMinChunkSize,
    setKnowledgeMinChunkSize,
    knowledgeChunkOverlap,
    setKnowledgeChunkOverlap,
    setShowLiterature,
    uploadKnowledgeFiles,
    renameKnowledgeFile,
    deleteKnowledgeFile,
    deleteKnowledgeFolder,
    mergeKnowledgeFolder,
    confirmKnowledgeProcessing,
    deleteLitJob,
    setExpandedJobId,
    showTraining,
    trainingEntrySource,
    trainingTab,
    setTrainingTab,
    trainingModelVersion,
    setTrainingModelVersion,
    trainingModelType,
    setTrainingModelType,
    maxRows,
    setMaxRows,
    handleStartTraining,
    trainingStarting,
    trainingRunStatus,
    handleCancelTraining,
    cancelling,
    trainingStatus,
    trainingLogs,
    trainingLogEndRef,
    fetchTrainingModels,
    trainingModelsLoading,
    trainingModels,
    expandedModelLogs,
    modelLogDataMap,
    handleActivateModel,
    handleViewModelLogs,
    handleDeleteModel,
    modelLogLoading,
    deletingModel,
  } = props;

  return (
    <>
      {isAgentMode && agentSidebarCollapsed && agentRecentChatsOpen && (
        <AgentRecentChatsPopover
          conversations={recentAgentConversations}
          activeSessionId={agentSessionId}
          onClose={() => setAgentRecentChatsOpen(false)}
          onSelectConversation={(conversation: any) => {
            selectAgentConversation(conversation);
            setAgentRecentChatsOpen(false);
          }}
        />
      )}

      <AgentHistorySearchDialog
        open={isAgentMode && agentHistorySearchOpen}
        search={agentHistorySearch}
        conversations={filteredAgentConversations}
        onSearchChange={setAgentHistorySearch}
        onClose={() => setAgentHistorySearchOpen(false)}
        onStartNew={() => {
          startNewAgentConversation();
          setAgentHistorySearchOpen(false);
        }}
        onSelectConversation={(conversation: any) => {
          selectAgentConversation(conversation);
          setAgentHistorySearchOpen(false);
        }}
      />

      <ProfilePage
        showProfileCenter={showProfileCenter}
        setShowProfileCenter={setShowProfileCenter}
        profileInitial={profileInitial}
        profileUsername={profileUsername}
        profileTab={profileTab}
        setProfileTab={setProfileTab}
        profileError={profileError}
        setProfileError={setProfileError}
        llmDraftDirty={llmDraftDirty}
        llmProvider={llmProvider}
        setLlmProvider={setLlmProvider}
        llmApiKey={llmApiKey}
        setLlmApiKey={setLlmApiKey}
        llmDisplayName={llmDisplayName}
        setLlmDisplayName={setLlmDisplayName}
        customProviderNames={customProviderNames}
        llmBaseUrl={llmBaseUrl}
        setLlmBaseUrl={setLlmBaseUrl}
        llmModelName={llmModelName}
        setLlmModelName={setLlmModelName}
        llmModelsLoading={llmModelsLoading}
        profileLlmModels={profileLlmModels}
        llmModelsNote={llmModelsNote}
        setLlmModels={setLlmModels}
        loadLlmConfig={loadLlmConfig}
        loadLlmModels={loadLlmModels}
        profileInfo={profileInfo}
        saveProfileLlmConfig={saveProfileLlmConfig}
        profileSaving={profileSaving}
        labCardTone={labCardTone}
        labRetrievalAvailable={labRetrievalAvailable}
        labOptimizationAvailable={labOptimizationAvailable}
        labServiceStatus={labServiceStatus}
        handleLabServiceAction={handleLabServiceAction}
        labServiceLoading={labServiceLoading}
        isDslAdmin={isDslAdmin}
        saveAuthSecurityConfig={saveAuthSecurityConfig}
        securitySaving={securitySaving}
        authSecurityConfig={authSecurityConfig}
        setAuthSecurityConfig={setAuthSecurityConfig}
        knowledgeBaseSecurityConfig={knowledgeBaseSecurityConfig}
        setKnowledgeBaseSecurityConfig={setKnowledgeBaseSecurityConfig}
        saveKnowledgeBaseSecurityConfig={saveKnowledgeBaseSecurityConfig}
        mineruProcessingConfig={mineruProcessingConfig}
        mineruUsage={mineruUsage}
        setMineruProcessingConfig={setMineruProcessingConfig}
        mineruApiKey={mineruApiKey}
        setMineruApiKey={setMineruApiKey}
        saveMineruProcessingConfig={saveMineruProcessingConfig}
        retrievalModelsConfig={retrievalModelsConfig}
        setRetrievalModelsConfig={setRetrievalModelsConfig}
        retrievalApiKey={retrievalApiKey}
        setRetrievalApiKey={setRetrievalApiKey}
        saveRetrievalModelsConfig={saveRetrievalModelsConfig}
        turnstileEnabled={turnstileEnabled}
        setTurnstileEnabled={setTurnstileEnabled}
        turnstileSiteKey={turnstileSiteKey}
        setTurnstileSiteKey={setTurnstileSiteKey}
        turnstileSecretKey={turnstileSecretKey}
        setTurnstileSecretKey={setTurnstileSecretKey}
        turnstileConfig={turnstileConfig}
        saveTurnstileAdminConfig={saveTurnstileAdminConfig}
        turnstileSaving={turnstileSaving}
        captchaConfig={captchaConfig}
        captchaProvider={captchaProvider}
        setCaptchaProvider={setCaptchaProvider}
        geetestCaptchaId={geetestCaptchaId}
        setGeetestCaptchaId={setGeetestCaptchaId}
        geetestPrivateKey={geetestPrivateKey}
        setGeetestPrivateKey={setGeetestPrivateKey}
        saveCaptchaAdminConfig={saveCaptchaAdminConfig}
      />

      {/* ========================= 工艺优化全屏页面 ========================= */}
      <OptimizePage
        showOptimizer={showOptimizer}
        setTrainingEntrySource={setTrainingEntrySource}
        setShowOptimizer={setShowOptimizer}
        setShowTraining={setShowTraining}
        hasOptimizerData={hasOptimizerData}
        optimizing={optimizing}
        optimizeResults={optimizeResults}
        optimizeResult={optimizeResult}
        optimizerRestoring={optimizerRestoring}
        handleToggleAllStandards={handleToggleAllStandards}
        selectedStandardIdx={selectedStandardIdx}
        activeOptimizerStandardRecords={activeOptimizerStandardRecords}
        activeOptimizerStandardColumns={activeOptimizerStandardColumns}
        handleSelectStandard={handleSelectStandard}
        targetYield={targetYield}
        setTargetYield={setTargetYield}
        targetTensile={targetTensile}
        setTargetTensile={setTargetTensile}
        targetElong={targetElong}
        setTargetElong={setTargetElong}
        optimizeAlgorithm={optimizeAlgorithm}
        setOptimizeAlgorithm={setOptimizeAlgorithm}
        optimizeMaxiter={optimizeMaxiter}
        setOptimizeMaxiter={setOptimizeMaxiter}
        optimizePopsize={optimizePopsize}
        setOptimizePopsize={setOptimizePopsize}
        handleOptimize={handleOptimize}
        optimizeProgress={optimizeProgress}
        requestOptimizeCancel={requestOptimizeCancel}
        optimizeStopping={optimizeStopping}
        optimizeError={optimizeError}
        currentOptimizingIdx={currentOptimizingIdx}
        setActiveResultTab={setActiveResultTab}
        activeResultTab={activeResultTab}
        optimizeLogs={optimizeLogs}
        perRecordLogs={perRecordLogs}
        tabTransition={tabTransition}
        tabViewMode={tabViewMode}
        setTabViewMode={setTabViewMode}
        paretoIdx={paretoIdx}
        setParetoIdx={setParetoIdx}
        exportingScheme={exportingScheme}
        setExportingScheme={setExportingScheme}
      />

      {/* ========================= 新增知识库面板 ========================= */}
      {showLiterature && (
        <LiteraturePage
          viewMode={knowledgeViewMode}
          openCreateView={openKnowledgeCreate}
          openAppendView={openKnowledgeAppend}
          openDetailView={openKnowledgeDetail}
          step={knowledgeStep}
          setStep={setKnowledgeStep}
          knowledgeName={knowledgeName}
          setKnowledgeName={setKnowledgeName}
          knowledgeFolder={knowledgeFolder}
          setKnowledgeFolder={setKnowledgeFolder}
          uploadedFiles={knowledgeUploadedFiles}
          uploadBusy={knowledgeUploadBusy}
          folders={litFolders}
          foldersLoading={litFoldersLoading}
          foldersLoaded={litFoldersLoaded}
          onRetryFolders={() => void fetchLitFolders()}
          literatureFiles={literatureFiles}
          literatureFilesLoading={literatureFilesLoading}
          selectedLiteratureFile={selectedLiteratureFile}
          setSelectedLiteratureFile={setSelectedLiteratureFile}
          literatureFilePreview={literatureFilePreview}
          literaturePreviewLoading={literaturePreviewLoading}
          jobs={litJobs}
          canContinueUpload={canContinueKnowledgeUpload}
          litLoading={litLoading}
          expandedJobId={expandedJobId}
          expandedJobLogs={expandedJobLogs}
          parseMode={knowledgeParseMode}
          setParseMode={setKnowledgeParseMode}
          extractImages={knowledgeExtractImages}
          setExtractImages={setKnowledgeExtractImages}
          extractOcr={knowledgeExtractOcr}
          setExtractOcr={setKnowledgeExtractOcr}
          extractTables={knowledgeExtractTables}
          setExtractTables={setKnowledgeExtractTables}
          enableFormula={knowledgeEnableFormula}
          setEnableFormula={setKnowledgeEnableFormula}
          pageRanges={knowledgePageRanges}
          setPageRanges={setKnowledgePageRanges}
          filterText={knowledgeFilterText}
          setFilterText={setKnowledgeFilterText}
          segmentMode={knowledgeSegmentMode}
          setSegmentMode={setKnowledgeSegmentMode}
          maxChunkSize={knowledgeMaxChunkSize}
          setMaxChunkSize={setKnowledgeMaxChunkSize}
          minChunkSize={knowledgeMinChunkSize}
          setMinChunkSize={setKnowledgeMinChunkSize}
          chunkOverlap={knowledgeChunkOverlap}
          setChunkOverlap={setKnowledgeChunkOverlap}
          mineruProcessingConfig={mineruProcessingConfig}
          onClose={() => setShowLiterature(false)}
          onUploadFiles={uploadKnowledgeFiles}
          onRenameFile={renameKnowledgeFile}
          onDeleteFile={deleteKnowledgeFile}
          onDeleteFolder={deleteKnowledgeFolder}
          onMergeFolder={mergeKnowledgeFolder}
          onConfirmProcessing={confirmKnowledgeProcessing}
          onDeleteJob={deleteLitJob}
          setExpandedJobId={setExpandedJobId}
        />
      )}

      {/* ========================= 妯″瀷璁粌闈㈡澘 ========================= */}
      <TrainingPage
        showTraining={showTraining}
        setShowTraining={setShowTraining}
        setShowOptimizer={setShowOptimizer}
        trainingEntrySource={trainingEntrySource}
        setTrainingEntrySource={setTrainingEntrySource}
        trainingTab={trainingTab}
        setTrainingTab={setTrainingTab}
        trainingModelVersion={trainingModelVersion}
        setTrainingModelVersion={setTrainingModelVersion}
        trainingModelType={trainingModelType}
        setTrainingModelType={setTrainingModelType}
        maxRows={maxRows}
        setMaxRows={setMaxRows}
        handleStartTraining={handleStartTraining}
        trainingStarting={trainingStarting}
        trainingRunStatus={trainingRunStatus}
        handleCancelTraining={handleCancelTraining}
        cancelling={cancelling}
        trainingStatus={trainingStatus}
        trainingLogs={trainingLogs}
        trainingLogEndRef={trainingLogEndRef}
        fetchTrainingModels={fetchTrainingModels}
        trainingModelsLoading={trainingModelsLoading}
        trainingModels={trainingModels}
        expandedModelLogs={expandedModelLogs}
        modelLogDataMap={modelLogDataMap}
        handleActivateModel={handleActivateModel}
        handleViewModelLogs={handleViewModelLogs}
        handleDeleteModel={handleDeleteModel}
        modelLogLoading={modelLogLoading}
        deletingModel={deletingModel}
      />
    </>
  );
}
