import React from "react";
import Lightbox from "../common/Lightbox";
import SystemStatsIndicator from "../common/SystemStatsIndicator";
import AdvancedFilterModal from "../search/AdvancedFilterModal";
import AgentSidebar from "../agent/AgentSidebar";
import RetrievalSidebarControls from "../search/RetrievalSidebarControls";
import RagAppOverlays from "./RagAppOverlays";
import RagMainContent from "./RagMainContent";
import { proxyImg, renderHighlighted } from "../../utils/searchRender";

type RagAppShellProps = Record<string, any>;

export default function RagAppShell(props: RagAppShellProps) {
  const {
    lightboxSrc,
    setLightboxSrc,
    showAdvancedFilter,
    steelMarkInput,
    steelGradeInput,
    steelMarkOptions,
    steelGradeOptions,
    filteredSteelMarkOptions,
    filteredSteelGradeOptions,
    steelMarkActiveIndex,
    steelGradeActiveIndex,
    steelMarkDropdownOpen,
    steelGradeDropdownOpen,
    steelMarkRef,
    steelGradeRef,
    steelMarkDropdownListRef,
    steelGradeDropdownListRef,
    setShowAdvancedFilter,
    handleAdvancedFilterClear,
    handleAdvancedFilterApply,
    handleSteelMarkInputChange,
    handleSteelGradeInputChange,
    handleSteelMarkFocus,
    handleSteelGradeFocus,
    handleSteelMarkInputKeyDown,
    handleSteelGradeInputKeyDown,
    toggleSteelMarkDropdown,
    toggleSteelGradeDropdown,
    handleSteelMarkSelect,
    handleSteelGradeSelect,
    previewSteelMarkOption,
    previewSteelGradeOption,
    isAgentMode,
    agentSidebarCollapsed,
    agentRecentChatsOpen,
    agentConversationSyncError,
    agentConversations,
    filteredAgentConversations,
    agentSessionId,
    renamingConversationId,
    renamingConversationTitle,
    agentConversationMenuId,
    profileInitial,
    profileUsername,
    setRenamingConversationTitle,
    setAgentSidebarCollapsed,
    startNewAgentConversation,
    setAgentRecentChatsOpen,
    setAgentHistorySearchOpen,
    selectAgentConversation,
    toggleAgentConversationPin,
    beginRenameAgentConversation,
    shareAgentConversation,
    deleteAgentConversation,
    setAgentConversationMenuId,
    commitRenameAgentConversation,
    openProfileCenter,
    agentModelMenuOpen,
    setAgentModelMenuOpen,
    availableChatModels,
    currentChatModelName,
    activeModelDisplayName,
    switchAgentModel,
    webSearchEnabled,
    toggleWebSearch,
    activeLlmConfig,
    currentChatProvider,
    currentChatBaseUrl,
    isStreaming,
    agentMessagesRef,
    agentMessagesEndRef,
    agentMessages,
    agentResponse,
    agentLoading,
    agentStreaming,
    agentError,
    agentProgress,
    query,
    setQuery,
    handleAgentSubmit,
    runAgent,
    agentAttachments,
    setAgentAttachments,
    beginEditAgentMessage,
    submitEditedAgentMessage,
    cancelEditAgentMessage,
    editingAgentMessageIndex,
    editingAgentMessageText,
    setEditingAgentMessageText,
    copyAgentMessage,
    copiedAgentMessageIndex,
    handleAgentFeedback,
    confirmAgentAction,
    clearAgentMemory,
    setAppMode,
    onSwitchRetrieval,
    onSwitchAgent,
    handleLogout,
    overviewData,
    overviewLoading,
    isAIMode,
    data,
    loading,
    aiAnswer,
    isProductionAI,
    stopAIStreaming,
    handleAIModeToggle,
    handleCompositionModeToggle,
    handleCoilMatchModeToggle,
    isCompositionMode,
    isCoilMatchMode,
    coilMatchLoading,
    coilMatchError,
    coilMatchResults,
    resultView,
    setResultView,
    includeProduction,
    setIncludeProduction,
    topK,
    setTopK,
    openAdvancedFilter,
    showFilters,
    setShowFilters,
    labServiceStatus,
    labServiceLoading,
    labRetrievalAvailable,
    labOptimizationAvailable,
    labCardTone,
    refreshLabServiceStatus,
    handleLabServiceAction,
    activeTab,
    visibleTabs,
    handleTabChange,
    handleExport,
    exporting,
    resultPaneRef,
    handleResultPaneScroll,
    totalProductionCount,
    displayedProductionRecords,
    setActiveTab,
    showProfileCenter,
    setShowProfileCenter,
    profileInfo,
    profileSaving,
    securitySaving,
    profileError,
    profileTab,
    setProfileTab,
    llmProvider,
    setLlmProvider,
    llmBaseUrl,
    setLlmBaseUrl,
    llmModelName,
    setLlmModelName,
    llmApiKey,
    setLlmApiKey,
    llmDisplayName,
    setLlmDisplayName,
    customProviderNames,
    llmModels,
    setLlmModels,
    llmModelsLoading,
    llmModelsNote,
    turnstileConfig,
    turnstileEnabled,
    setTurnstileEnabled,
    turnstileSiteKey,
    setTurnstileSiteKey,
    turnstileSecretKey,
    setTurnstileSecretKey,
    turnstileSaving,
    captchaConfig,
    captchaProvider,
    setCaptchaProvider,
    geetestCaptchaId,
    setGeetestCaptchaId,
    geetestPrivateKey,
    setGeetestPrivateKey,
    saveCaptchaAdminConfig,
    authSecurityConfig,
    setAuthSecurityConfig,
    knowledgeBaseSecurityConfig,
    setKnowledgeBaseSecurityConfig,
    saveKnowledgeBaseSecurityConfig,
    mineruProcessingConfig,
    mineruUsage,
    setMineruProcessingConfig,
    mineruApiKey,
    setMineruApiKey,
    saveMineruProcessingConfig,
    retrievalModelsConfig,
    setRetrievalModelsConfig,
    retrievalApiKey,
    setRetrievalApiKey,
    saveRetrievalModelsConfig,
    isDslAdmin,
    llmDraftDirty,
    profileLlmModels,
    loadLlmModels,
    loadLlmConfig,
    saveProfileLlmConfig,
    saveTurnstileAdminConfig,
    saveAuthSecurityConfig,
    showOptimizer,
    setShowOptimizer,
    optimizerComposition,
    selectedStandardIdx,
    targetYield,
    setTargetYield,
    targetTensile,
    setTargetTensile,
    targetElong,
    setTargetElong,
    optimizing,
    optimizeResult,
    optimizeResults,
    activeResultTab,
    setActiveResultTab,
    optimizeProgress,
    optimizeMaxiter,
    setOptimizeMaxiter,
    optimizePopsize,
    setOptimizePopsize,
    optimizeAlgorithm,
    setOptimizeAlgorithm,
    optimizeError,
    optimizeLogs,
    optimizeStopping,
    optimizerRestoring,
    currentOptimizingIdx,
    perRecordLogs,
    paretoIdx,
    setParetoIdx,
    tabViewMode,
    setTabViewMode,
    tabTransition,
    activeOptimizerStandardRecords,
    activeOptimizerStandardColumns,
    hasOptimizerData,
    handleOpenOptimizer,
    handleSelectStandard,
    handleToggleAllStandards,
    handleOptimize,
    requestOptimizeCancel,
    exportingScheme,
    setExportingScheme,
    showTraining,
    setShowTraining,
    trainingEntrySource,
    setTrainingEntrySource,
    trainingTab,
    setTrainingTab,
    trainingModelVersion,
    setTrainingModelVersion,
    trainingModelType,
    setTrainingModelType,
    maxRows,
    setMaxRows,
    handleStartTraining,
    trainingStarting,
    trainingRunStatus,
    handleCancelTraining,
    cancelling,
    trainingStatus,
    trainingLogs,
    trainingLogEndRef,
    fetchTrainingModels,
    trainingModelsLoading,
    trainingModels,
    expandedModelLogs,
    modelLogDataMap,
    handleActivateModel,
    handleViewModelLogs,
    handleDeleteModel,
    modelLogLoading,
    deletingModel,
    showLiterature,
    setShowLiterature,
    knowledgeViewMode,
    openKnowledgeCreate,
    openKnowledgeAppend,
    openKnowledgeDetail,
    litFolders, litFoldersLoading, litFoldersLoaded, fetchLitFolders,
    literatureFiles,
    literatureFilesLoading,
    selectedLiteratureFile,
    setSelectedLiteratureFile,
    literatureFilePreview,
    literaturePreviewLoading,
    litJobs,
    litLoading,
    expandedJobLogs,
    expandedJobId,
    setExpandedJobId,
    knowledgeStep,
    setKnowledgeStep,
    knowledgeName,
    setKnowledgeName,
    knowledgeFolder,
    setKnowledgeFolder,
    knowledgeUploadedFiles,
    knowledgeUploadBusy,
    knowledgeParseMode,
    setKnowledgeParseMode,
    knowledgeExtractImages,
    setKnowledgeExtractImages,
    knowledgeExtractOcr,
    setKnowledgeExtractOcr,
    knowledgeExtractTables,
    setKnowledgeExtractTables,
    knowledgeEnableFormula,
    setKnowledgeEnableFormula,
    knowledgePageRanges,
    setKnowledgePageRanges,
    knowledgeFilterText,
    setKnowledgeFilterText,
    knowledgeSegmentMode,
    setKnowledgeSegmentMode,
    knowledgeMaxChunkSize,
    setKnowledgeMaxChunkSize,
    knowledgeMinChunkSize,
    setKnowledgeMinChunkSize,
    knowledgeChunkOverlap,
    setKnowledgeChunkOverlap,
    openKnowledgeWizard,
    uploadKnowledgeFiles,
    renameKnowledgeFile,
    deleteKnowledgeFile,
    deleteKnowledgeFolder,
    mergeKnowledgeFolder,
    selectedKnowledgeFolder,
    canContinueKnowledgeUpload,
    confirmKnowledgeProcessing,
    deleteLitJob,
    agentHistorySearchOpen,
    agentHistorySearch,
    setAgentHistorySearch,
    recentAgentConversations,
    adviceModeEnabled,
    yieldRp02Value,
    setYieldRp02Value,
    tensileStrengthValue,
    setTensileStrengthValue,
    elongationValue,
    setElongationValue,
    slabWidthMin,
    setSlabWidthMin,
    slabWidthMax,
    setSlabWidthMax,
    slabThicknessMin,
    setSlabThicknessMin,
    slabThicknessMax,
    setSlabThicknessMax,
    yieldRp02Min,
    setYieldRp02Min,
    yieldRp02Max,
    setYieldRp02Max,
    tensileStrengthMin,
    setTensileStrengthMin,
    tensileStrengthMax,
    setTensileStrengthMax,
    elongationMin,
    setElongationMin,
    elongationMax,
    setElongationMax,
    handleSearch,
    steelMark,
    steelGrade,
    aiAnswerRef,
    setProfileError,
    setRenamingConversationId,
  } = props;

return (
  <div className="relative h-[100dvh] bg-slate-50 text-slate-900 font-sans antialiased overflow-hidden selection:bg-indigo-100">
    {/* ---- subtle background gradient ---- */}
    <div className="pointer-events-none fixed inset-0 overflow-hidden">
      <div className="absolute -top-[40%] -left-[20%] h-[80vh] w-[60vw] rounded-full bg-indigo-100/50 blur-[120px]" />
      <div className="absolute -bottom-[30%] -right-[15%] h-[60vh] w-[50vw] rounded-full bg-cyan-50/50 blur-[100px]" />
    </div>

    {/* ---- lightbox overlay ---- */}
    {lightboxSrc && (
      <Lightbox src={lightboxSrc} alt="preview" onClose={() => setLightboxSrc(null)} />
    )}

    {/* ---- advanced filter modal ---- */}
    <AdvancedFilterModal
      open={showAdvancedFilter}
      steelMarkInput={steelMarkInput}
      steelGradeInput={steelGradeInput}
      steelMarkOptions={steelMarkOptions}
      steelGradeOptions={steelGradeOptions}
      filteredSteelMarkOptions={filteredSteelMarkOptions}
      filteredSteelGradeOptions={filteredSteelGradeOptions}
      steelMarkActiveIndex={steelMarkActiveIndex}
      steelGradeActiveIndex={steelGradeActiveIndex}
      steelMarkDropdownOpen={steelMarkDropdownOpen}
      steelGradeDropdownOpen={steelGradeDropdownOpen}
      steelMarkRef={steelMarkRef}
      steelGradeRef={steelGradeRef}
      steelMarkDropdownListRef={steelMarkDropdownListRef}
      steelGradeDropdownListRef={steelGradeDropdownListRef}
      onClose={() => setShowAdvancedFilter(false)}
      onClear={handleAdvancedFilterClear}
      onApply={handleAdvancedFilterApply}
      onSteelMarkInputChange={handleSteelMarkInputChange}
      onSteelGradeInputChange={handleSteelGradeInputChange}
      onSteelMarkFocus={handleSteelMarkFocus}
      onSteelGradeFocus={handleSteelGradeFocus}
      onSteelMarkKeyDown={handleSteelMarkInputKeyDown}
      onSteelGradeKeyDown={handleSteelGradeInputKeyDown}
      onToggleSteelMarkDropdown={toggleSteelMarkDropdown}
      onToggleSteelGradeDropdown={toggleSteelGradeDropdown}
      onSteelMarkSelect={handleSteelMarkSelect}
      onSteelGradeSelect={handleSteelGradeSelect}
      onSteelMarkPreview={previewSteelMarkOption}
      onSteelGradePreview={previewSteelGradeOption}
    />
    <div className="relative z-10 flex h-[100dvh]">
      {/* ========================= LEFT SIDEBAR ========================= */}
      <AgentSidebar
        isAgentMode={isAgentMode}
        collapsed={agentSidebarCollapsed}
        recentChatsOpen={agentRecentChatsOpen}
        conversationSyncError={agentConversationSyncError}
        conversations={agentConversations}
        filteredConversations={filteredAgentConversations}
        activeSessionId={agentSessionId}
        renamingConversationId={renamingConversationId}
        renamingConversationTitle={renamingConversationTitle}
        conversationMenuId={agentConversationMenuId}
        profileInitial={profileInitial}
        profileUsername={profileUsername}
        setRenamingConversationTitle={setRenamingConversationTitle}
        onExpand={() => {
          setAgentSidebarCollapsed(false);
          setAgentRecentChatsOpen(false);
        }}
        onCollapse={() => setAgentSidebarCollapsed(true)}
        onStartNew={() => {
          startNewAgentConversation();
          setAgentRecentChatsOpen(false);
          setAgentHistorySearchOpen(false);
        }}
        onOpenHistorySearch={() => {
          setAgentRecentChatsOpen(false);
          setAgentHistorySearchOpen(true);
          setAgentHistorySearch("");
        }}
        onToggleRecentChats={() => {
          setAgentHistorySearchOpen(false);
          setAgentRecentChatsOpen((open: boolean) => !open);
        }}
        onSelectConversation={selectAgentConversation}
        onCommitRename={commitRenameAgentConversation}
        onCancelRename={() => setRenamingConversationId(null)}
        onTogglePin={toggleAgentConversationPin}
        onToggleConversationMenu={(conversation) => setAgentConversationMenuId(agentConversationMenuId === conversation.sessionId ? null : conversation.sessionId)}
        onShareConversation={shareAgentConversation}
        onBeginRename={beginRenameAgentConversation}
        onDeleteConversation={deleteAgentConversation}
        onOpenProfile={openProfileCenter}
        onLogout={handleLogout}
        onSwitchRetrieval={onSwitchRetrieval}
        onSwitchAgent={onSwitchAgent}
      >
        <RetrievalSidebarControls
          overviewData={overviewData}
          adviceModeEnabled={adviceModeEnabled}
          isCoilMatchMode={isCoilMatchMode}
          yieldRp02Value={yieldRp02Value}
          setYieldRp02Value={setYieldRp02Value}
          tensileStrengthValue={tensileStrengthValue}
          setTensileStrengthValue={setTensileStrengthValue}
          elongationValue={elongationValue}
          setElongationValue={setElongationValue}
          slabWidthMin={slabWidthMin}
          setSlabWidthMin={setSlabWidthMin}
          slabWidthMax={slabWidthMax}
          setSlabWidthMax={setSlabWidthMax}
          slabThicknessMin={slabThicknessMin}
          setSlabThicknessMin={setSlabThicknessMin}
          slabThicknessMax={slabThicknessMax}
          setSlabThicknessMax={setSlabThicknessMax}
          yieldRp02Min={yieldRp02Min}
          setYieldRp02Min={setYieldRp02Min}
          yieldRp02Max={yieldRp02Max}
          setYieldRp02Max={setYieldRp02Max}
          tensileStrengthMin={tensileStrengthMin}
          setTensileStrengthMin={setTensileStrengthMin}
          tensileStrengthMax={tensileStrengthMax}
          setTensileStrengthMax={setTensileStrengthMax}
          elongationMin={elongationMin}
          setElongationMin={setElongationMin}
          elongationMax={elongationMax}
          setElongationMax={setElongationMax}
          topK={topK}
          setTopK={setTopK}
          includeProduction={includeProduction}
          setIncludeProduction={setIncludeProduction}
        />
      </AgentSidebar>

      <RagMainContent
        isAgentMode={isAgentMode}
        agentSidebarCollapsed={agentSidebarCollapsed}
        onOpenSidebar={() => { setAgentSidebarCollapsed(false); setAgentRecentChatsOpen(false); }}
        setAppMode={setAppMode}
        openKnowledgeWizard={openKnowledgeWizard}
        setTrainingEntrySource={setTrainingEntrySource}
        setShowTraining={setShowTraining}
        handleOpenOptimizer={handleOpenOptimizer}
        optimizing={optimizing}
        query={query}
        setQuery={setQuery}
        handleSearch={handleSearch}
        loading={loading}
        coilMatchLoading={coilMatchLoading}
        includeProduction={includeProduction}
        adviceModeEnabled={adviceModeEnabled}
        isCoilMatchMode={isCoilMatchMode}
        isAIMode={isAIMode}
        handleAIModeToggle={handleAIModeToggle}
        handleCompositionModeToggle={handleCompositionModeToggle}
        handleCoilMatchModeToggle={handleCoilMatchModeToggle}
        isCompositionMode={isCompositionMode}
        data={data}
        resultView={resultView}
        setResultView={setResultView}
        isStreaming={isStreaming}
        isProductionAI={isProductionAI}
        stopAIStreaming={stopAIStreaming}
        aiAnswerRef={aiAnswerRef}
        aiAnswer={aiAnswer}
        steelMark={steelMark}
        steelGrade={steelGrade}
        setActiveTab={setActiveTab}
        visibleTabs={visibleTabs}
        activeTab={activeTab}
        handleTabChange={handleTabChange}
        openAdvancedFilter={openAdvancedFilter}
        handleExport={handleExport}
        exporting={exporting}
        resultPaneRef={resultPaneRef}
        handleResultPaneScroll={handleResultPaneScroll}
        totalProductionCount={totalProductionCount}
        displayedProductionRecords={displayedProductionRecords}
        renderHighlighted={renderHighlighted}
        proxyImg={proxyImg}
        setLightboxSrc={setLightboxSrc}
        coilMatchResults={coilMatchResults}
        coilMatchError={coilMatchError}
        agentMessagesRef={agentMessagesRef}
        agentMessagesEndRef={agentMessagesEndRef}
        agentMessages={agentMessages}
        agentLoading={agentLoading}
        agentStreaming={agentStreaming}
        agentError={agentError}
        agentProgress={agentProgress}
        agentResponse={agentResponse}
        agentSessionId={agentSessionId}
        editingAgentMessageIndex={editingAgentMessageIndex}
        editingAgentMessageText={editingAgentMessageText}
        copiedAgentMessageIndex={copiedAgentMessageIndex}
        agentModelMenuOpen={agentModelMenuOpen}
        availableChatModels={availableChatModels}
        currentChatModelName={currentChatModelName}
        activeModelDisplayName={activeModelDisplayName}
        setEditingAgentMessageText={setEditingAgentMessageText}
        setAgentModelMenuOpen={setAgentModelMenuOpen}
        cancelEditAgentMessage={cancelEditAgentMessage}
        submitEditedAgentMessage={submitEditedAgentMessage}
        copyAgentMessage={copyAgentMessage}
        beginEditAgentMessage={beginEditAgentMessage}
        handleAgentFeedback={handleAgentFeedback}
        confirmAgentAction={confirmAgentAction}
        handleAgentSubmit={handleAgentSubmit}
        switchAgentModel={switchAgentModel}
        webSearchEnabled={webSearchEnabled}
        toggleWebSearch={toggleWebSearch}
        agentAttachments={agentAttachments}
        setAgentAttachments={setAgentAttachments}
      />
    </div>

    <RagAppOverlays
      isAgentMode={isAgentMode}
      agentSidebarCollapsed={agentSidebarCollapsed}
      agentRecentChatsOpen={agentRecentChatsOpen}
      recentAgentConversations={recentAgentConversations}
      agentSessionId={agentSessionId}
      setAgentRecentChatsOpen={setAgentRecentChatsOpen}
      selectAgentConversation={selectAgentConversation}
      agentHistorySearchOpen={agentHistorySearchOpen}
      agentHistorySearch={agentHistorySearch}
      filteredAgentConversations={filteredAgentConversations}
      setAgentHistorySearch={setAgentHistorySearch}
      setAgentHistorySearchOpen={setAgentHistorySearchOpen}
      startNewAgentConversation={startNewAgentConversation}
      showProfileCenter={showProfileCenter}
      setShowProfileCenter={setShowProfileCenter}
      profileInitial={profileInitial}
      profileUsername={profileUsername}
      profileTab={profileTab}
      setProfileTab={setProfileTab}
      profileError={profileError}
      setProfileError={setProfileError}
      llmDraftDirty={llmDraftDirty}
      llmProvider={llmProvider}
      setLlmProvider={setLlmProvider}
      llmApiKey={llmApiKey}
      setLlmApiKey={setLlmApiKey}
      llmDisplayName={llmDisplayName}
      setLlmDisplayName={setLlmDisplayName}
      customProviderNames={customProviderNames}
      llmBaseUrl={llmBaseUrl}
      setLlmBaseUrl={setLlmBaseUrl}
      llmModelName={llmModelName}
      setLlmModelName={setLlmModelName}
      llmModelsLoading={llmModelsLoading}
      profileLlmModels={profileLlmModels}
      llmModelsNote={llmModelsNote}
      setLlmModels={setLlmModels}
      loadLlmConfig={loadLlmConfig}
      loadLlmModels={loadLlmModels}
      profileInfo={profileInfo}
      saveProfileLlmConfig={saveProfileLlmConfig}
      profileSaving={profileSaving}
      labCardTone={labCardTone}
      labRetrievalAvailable={labRetrievalAvailable}
      labOptimizationAvailable={labOptimizationAvailable}
      labServiceStatus={labServiceStatus}
      handleLabServiceAction={handleLabServiceAction}
      labServiceLoading={labServiceLoading}
      isDslAdmin={isDslAdmin}
      saveAuthSecurityConfig={saveAuthSecurityConfig}
      securitySaving={securitySaving}
      authSecurityConfig={authSecurityConfig}
      setAuthSecurityConfig={setAuthSecurityConfig}
      knowledgeBaseSecurityConfig={knowledgeBaseSecurityConfig}
      setKnowledgeBaseSecurityConfig={setKnowledgeBaseSecurityConfig}
      saveKnowledgeBaseSecurityConfig={saveKnowledgeBaseSecurityConfig}
      mineruProcessingConfig={mineruProcessingConfig}
      mineruUsage={mineruUsage}
      setMineruProcessingConfig={setMineruProcessingConfig}
      mineruApiKey={mineruApiKey}
      setMineruApiKey={setMineruApiKey}
      saveMineruProcessingConfig={saveMineruProcessingConfig}
      retrievalModelsConfig={retrievalModelsConfig}
      setRetrievalModelsConfig={setRetrievalModelsConfig}
      retrievalApiKey={retrievalApiKey}
      setRetrievalApiKey={setRetrievalApiKey}
      saveRetrievalModelsConfig={saveRetrievalModelsConfig}
      turnstileEnabled={turnstileEnabled}
      setTurnstileEnabled={setTurnstileEnabled}
      turnstileSiteKey={turnstileSiteKey}
      setTurnstileSiteKey={setTurnstileSiteKey}
      turnstileSecretKey={turnstileSecretKey}
      setTurnstileSecretKey={setTurnstileSecretKey}
      turnstileConfig={turnstileConfig}
      saveTurnstileAdminConfig={saveTurnstileAdminConfig}
      turnstileSaving={turnstileSaving}
      captchaConfig={captchaConfig}
      captchaProvider={captchaProvider}
      setCaptchaProvider={setCaptchaProvider}
      geetestCaptchaId={geetestCaptchaId}
      setGeetestCaptchaId={setGeetestCaptchaId}
      geetestPrivateKey={geetestPrivateKey}
      setGeetestPrivateKey={setGeetestPrivateKey}
      saveCaptchaAdminConfig={saveCaptchaAdminConfig}
      showOptimizer={showOptimizer}
      setTrainingEntrySource={setTrainingEntrySource}
      setShowOptimizer={setShowOptimizer}
      setShowTraining={setShowTraining}
      hasOptimizerData={hasOptimizerData}
      optimizing={optimizing}
      optimizeResults={optimizeResults}
      optimizeResult={optimizeResult}
      optimizerRestoring={optimizerRestoring}
      handleToggleAllStandards={handleToggleAllStandards}
      selectedStandardIdx={selectedStandardIdx}
      activeOptimizerStandardRecords={activeOptimizerStandardRecords}
      activeOptimizerStandardColumns={activeOptimizerStandardColumns}
      handleSelectStandard={handleSelectStandard}
      targetYield={targetYield}
      setTargetYield={setTargetYield}
      targetTensile={targetTensile}
      setTargetTensile={setTargetTensile}
      targetElong={targetElong}
      setTargetElong={setTargetElong}
      optimizeAlgorithm={optimizeAlgorithm}
      setOptimizeAlgorithm={setOptimizeAlgorithm}
      optimizeMaxiter={optimizeMaxiter}
      setOptimizeMaxiter={setOptimizeMaxiter}
      optimizePopsize={optimizePopsize}
      setOptimizePopsize={setOptimizePopsize}
      handleOptimize={handleOptimize}
      optimizeProgress={optimizeProgress}
      requestOptimizeCancel={requestOptimizeCancel}
      optimizeStopping={optimizeStopping}
      optimizeError={optimizeError}
      currentOptimizingIdx={currentOptimizingIdx}
      setActiveResultTab={setActiveResultTab}
      activeResultTab={activeResultTab}
      optimizeLogs={optimizeLogs}
      perRecordLogs={perRecordLogs}
      tabTransition={tabTransition}
      tabViewMode={tabViewMode}
      setTabViewMode={setTabViewMode}
      paretoIdx={paretoIdx}
      setParetoIdx={setParetoIdx}
      exportingScheme={exportingScheme}
      setExportingScheme={setExportingScheme}
      showLiterature={showLiterature}
      knowledgeViewMode={knowledgeViewMode}
      openKnowledgeCreate={openKnowledgeCreate}
      openKnowledgeAppend={openKnowledgeAppend}
      openKnowledgeDetail={openKnowledgeDetail}
      knowledgeStep={knowledgeStep}
      setKnowledgeStep={setKnowledgeStep}
      knowledgeName={knowledgeName}
      setKnowledgeName={setKnowledgeName}
      knowledgeFolder={knowledgeFolder}
      setKnowledgeFolder={setKnowledgeFolder}
      knowledgeUploadedFiles={knowledgeUploadedFiles}
      knowledgeUploadBusy={knowledgeUploadBusy}
      litFolders={litFolders} litFoldersLoading={litFoldersLoading} litFoldersLoaded={litFoldersLoaded} fetchLitFolders={fetchLitFolders}
      literatureFiles={literatureFiles}
      literatureFilesLoading={literatureFilesLoading}
      selectedLiteratureFile={selectedLiteratureFile}
      setSelectedLiteratureFile={setSelectedLiteratureFile}
      literatureFilePreview={literatureFilePreview}
      literaturePreviewLoading={literaturePreviewLoading}
      litJobs={litJobs}
      canContinueKnowledgeUpload={canContinueKnowledgeUpload}
      litLoading={litLoading}
      expandedJobId={expandedJobId}
      expandedJobLogs={expandedJobLogs}
      knowledgeParseMode={knowledgeParseMode}
      setKnowledgeParseMode={setKnowledgeParseMode}
      knowledgeExtractImages={knowledgeExtractImages}
      setKnowledgeExtractImages={setKnowledgeExtractImages}
      knowledgeExtractOcr={knowledgeExtractOcr}
      setKnowledgeExtractOcr={setKnowledgeExtractOcr}
      knowledgeExtractTables={knowledgeExtractTables}
      setKnowledgeExtractTables={setKnowledgeExtractTables}
      knowledgeEnableFormula={knowledgeEnableFormula}
      setKnowledgeEnableFormula={setKnowledgeEnableFormula}
      knowledgePageRanges={knowledgePageRanges}
      setKnowledgePageRanges={setKnowledgePageRanges}
      knowledgeFilterText={knowledgeFilterText}
      setKnowledgeFilterText={setKnowledgeFilterText}
      knowledgeSegmentMode={knowledgeSegmentMode}
      setKnowledgeSegmentMode={setKnowledgeSegmentMode}
      knowledgeMaxChunkSize={knowledgeMaxChunkSize}
      setKnowledgeMaxChunkSize={setKnowledgeMaxChunkSize}
      knowledgeMinChunkSize={knowledgeMinChunkSize}
      setKnowledgeMinChunkSize={setKnowledgeMinChunkSize}
      knowledgeChunkOverlap={knowledgeChunkOverlap}
      setKnowledgeChunkOverlap={setKnowledgeChunkOverlap}
      setShowLiterature={setShowLiterature}
      uploadKnowledgeFiles={uploadKnowledgeFiles}
      renameKnowledgeFile={renameKnowledgeFile}
      deleteKnowledgeFile={deleteKnowledgeFile}
      deleteKnowledgeFolder={deleteKnowledgeFolder}
      mergeKnowledgeFolder={mergeKnowledgeFolder}
      confirmKnowledgeProcessing={confirmKnowledgeProcessing}
      deleteLitJob={deleteLitJob}
      setExpandedJobId={setExpandedJobId}
      showTraining={showTraining}
      trainingEntrySource={trainingEntrySource}
      trainingTab={trainingTab}
      setTrainingTab={setTrainingTab}
      trainingModelVersion={trainingModelVersion}
      setTrainingModelVersion={setTrainingModelVersion}
      trainingModelType={trainingModelType}
      setTrainingModelType={setTrainingModelType}
      maxRows={maxRows}
      setMaxRows={setMaxRows}
      handleStartTraining={handleStartTraining}
      trainingStarting={trainingStarting}
      trainingRunStatus={trainingRunStatus}
      handleCancelTraining={handleCancelTraining}
      cancelling={cancelling}
      trainingStatus={trainingStatus}
      trainingLogs={trainingLogs}
      trainingLogEndRef={trainingLogEndRef}
      fetchTrainingModels={fetchTrainingModels}
      trainingModelsLoading={trainingModelsLoading}
      trainingModels={trainingModels}
      expandedModelLogs={expandedModelLogs}
      modelLogDataMap={modelLogDataMap}
      handleActivateModel={handleActivateModel}
      handleViewModelLogs={handleViewModelLogs}
      handleDeleteModel={handleDeleteModel}
      modelLogLoading={modelLogLoading}
      deletingModel={deletingModel}
    />

    {/* ---- system stats indicator ---- */}
    {(showTraining || showOptimizer) && <SystemStatsIndicator />}

  </div>
);
}
